// Fonts
export const FONTS_LOADED = 'FONTS_LOADED';

// Options
export const SET_ACTIVE_PRESET = 'SET_ACTIVE_PRESET';
export const SET_UNLIMITED_PASSWORD_LENGTH = 'SET_UNLIMITED_PASSWORD_LENGTH';
export const SET_LIST_OPTION = 'SET_LIST_OPTION';
export const SET_PASSWORD_OPTION = 'SET_PASSWORD_OPTION';

// Passwords
export const GENERATE_MAIN_PASSWORD = 'GENERATE_MAIN_PASSWORD';
export const GENERATE_PASSWORD_LIST = 'GENERATE_PASSWORD_LIST';
export const SET_GENERATION_ERROR = 'SET_GENERATION_ERROR';

// Presets
export const ADD_PRESET = 'ADD_PRESET';
export const EDIT_PRESET = 'EDIT_PRESET';
export const REMOVE_PRESET = 'REMOVE_PRESET';

// Tooltips
export const SET_TOOLTIP_TEXT = 'SET_TOOLTIP_TEXT';